"""add_feishu_digest_tables

Revision ID: f1c88aafbd4a
Revises: 7c6b419ed52d
Create Date: 2026-06-09 01:19:19.206185

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1c88aafbd4a"
down_revision: Union[str, None] = "7c6b419ed52d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "digest_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("target_channel", sa.String(length=20), nullable=False),
        sa.Column("feishu_chat_id", sa.String(length=100), nullable=True),
        sa.Column("message_id", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "window_start", "window_end", "target_channel", name="uq_digest_run_window"
        ),
    )
    op.create_index(op.f("ix_digest_runs_user_id"), "digest_runs", ["user_id"], unique=False)
    op.create_table(
        "digest_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("folder_id", sa.String(length=36), nullable=True),
        sa.Column("category_name", sa.String(length=100), nullable=False),
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("title_zh", sa.String(length=1000), nullable=True),
        sa.Column("summary_zh", sa.Text(), nullable=True),
        sa.Column("fulltext_zh", sa.Text(), nullable=True),
        sa.Column("fulltext_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("feishu_message_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["folder_id"], ["folders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["digest_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "code", name="uq_digest_item_code"),
        sa.UniqueConstraint("run_id", "entry_id", name="uq_digest_item_entry"),
    )
    op.create_index(
        "idx_digest_item_user_entry", "digest_items", ["user_id", "entry_id"], unique=False
    )
    op.create_index(op.f("ix_digest_items_entry_id"), "digest_items", ["entry_id"], unique=False)
    op.create_index(op.f("ix_digest_items_folder_id"), "digest_items", ["folder_id"], unique=False)
    op.create_index(op.f("ix_digest_items_run_id"), "digest_items", ["run_id"], unique=False)
    op.create_index(op.f("ix_digest_items_user_id"), "digest_items", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_digest_items_user_id"), table_name="digest_items")
    op.drop_index(op.f("ix_digest_items_run_id"), table_name="digest_items")
    op.drop_index(op.f("ix_digest_items_folder_id"), table_name="digest_items")
    op.drop_index(op.f("ix_digest_items_entry_id"), table_name="digest_items")
    op.drop_index("idx_digest_item_user_entry", table_name="digest_items")
    op.drop_table("digest_items")
    op.drop_index(op.f("ix_digest_runs_user_id"), table_name="digest_runs")
    op.drop_table("digest_runs")
    # ### end Alembic commands ###
